version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: chessapp
    volumes:
      - chessapp-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    image: chessapp-api
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports: 
      - 5000:5000
    depends_on:
      - db
    environment:
      HOST: db
      USER: chessapp
      PASSWORD: password
      JWT_KEY: chesschesschess
  client:
    image: chessapp
    build:
      dockerfile: Dockerfile
      context: "./chessapp"
    ports:
      - 3000:3000

volumes:
  chessapp-data: